language: java

sudo: false
dist: trusty

jdk:
  -oraclejdk11

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

matrix:
  include:
  - env: JDK='Oracle JDK 11'
    install: . ./install-jdk.sh -F 11 -L BCL

script:
  - mvn test -B
  - echo PATH = ${PATH}
  - echo JAVA_HOME = ${JAVA_HOME}
  - java -version